server:
  port: 8082
spring:
  application:
    name: alarm-confirm
  datasource:
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
    url: jdbc:sqlserver://10.50.238.161:1433;DatabaseName=Alarm
    username: sa
    password: 1IllI1|1Il
  redis:
   lettuce:
     pool:
       max-active: 880
       max-idle: 880
       min-idle: 880
       max-wait: 100
   cluster:
     nodes: 10.50.238.174:6379,10.50.238.170:6379,10.50.238.144:6379,10.50.238.169:6379,10.50.238.162:6379
     max-redirects: 3
   timeout: 5000

#  # nacos 配置
#  cloud:
#    nacos:
#      discovery:
#        server-addr:
#
